language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: iB1c6IaFQnuhwCejbYku3EJbZuDcH2LGgtnLDzaDKrrDsPvwTiy0xNJmO9zjCbPgiNpNnMhtJ+VfQcE+H2EDOdvljuJIsa4/4bD6VcRYbV7QJuG3XxcZ/xM6MGPjBUMQcglRm0HqnQeKVRQ9Kq6ke9BcI9uwqSNErXWrmKYdjwzhQA0CEQfWhYsg5KBRZgueF7X6ymAyaOuBXcI4C54bmjvsp/88q8MZy4i/a0XBSrlmc9cSDC+9Ibc129/dQ/+7vYBqI6HUWZh1eshP8LJ5+TD+nT1UwBcEFQpi+7ZNEIDhDCrbC22qiRhLaVuKZU8hry+SlOXem0FdWiXS4KutlMqO75Drbr/dbDoy9CP2SxJVRjnzC9E/3YXmU/CMCssOMeZQVQ4Ztwp6TGJclR3OuPi+RO2nz+WMhV3QEfDYMHzjeeOrjY4f0zfSeIKfiVC9f8MTezGEdqyb19ZCnx97kwczgQLojxCw56VWFsCgkbUw/8XLLMNt8NMmLcV2Q6yKDIg6n9nEwVN17GDYHnUENs+AIi6EWXO1TkY89ak7ob9t+3Uq05hLRMn8cJkKy6BD3bD+4AY91Rjj4hR9ux8eycIa6NDFcMYDLO1UIZPXxLORr9LLnFaOb+qPgRzLEPtiXnWwQYr1eVnENOmvO67fA6zs/qziG9pHrn8iopEgfz0=
  - secure: jKUwQPvNPh4m5OmNCVpIDKDzE/37QFS4XfQXm4kg3Na/i2fq/d/ZE/6hpP/m7EBN8JqPpkUH8oxi8wvuHnIoFOLkrLPlBMIxStcNlZJk1t3dudCL30lQ6ZkjZPEg2nk8Y88sRhvdyQWCQz+mjx3XfamB768XdrHj5RP8iNdSOvjOZM+i9H76e5zcHJAuIrN8WS1aSaIMeoIjp5WVT+7l8cxYEEajxJd3fFnNuv+dGL/+3J0ahR0gk/V1WdXg3B8zFyoaBSiyL7QoNWpfWswLgw4Y7j+39n3J+FAbNnBlZ6wYN8LpznWNTeVOu96VrlleH/bfQ5xUauraeiFp42Z2RU/0xA/v4ZBHJS2eI8c8kJbyLqG4Qgq2tTDDe8EGEqewl1g0PPBM3+1kgF4/aYbXBhyhSaexSAVHAl/5/l/AaNN4gqCwqmG2C2I6tWWR1UVqRSTaW3CjSyCsMx5F2QPU8D2u+Pak4U+yjHtFdS0dEbPaFyNfQSmrll0E2NozACODnP1Ha94wWPPFA75D5tOva0OyvCORCNNo+1l22sCVHDjzqeNB4vdXJar4UpOmdyUciwQSFxF19qBMfb+K+1Yec3Jc394OsPw79D+7SGfW0WYIoV+3qANGIRQuN8NvANz/OGiSXc1C5IOSsX3hDsE0SANYChQW15/qGS+kwASaj6U=
