language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: vmm/ItmIyN5TCrchb+qljenDAHD1J/6n3gpcDsEpOSiNB7esMU03aMuXKxy1AJAehwwqqUl43U8Wb9i2cRZrC8fkxEgfnQkKAsZIrMV45W2EznGt3vCTLWKkOq0hNn3XgSmsUr2/dqlmNgIAi2nJtQ7KF5I9ayZt+W0S5wx72L7LcVTEm4Jz4G9R5GWCf93dImMjW6FJwydR07GMbte0zIFkmFEQXzR6HPTjMXFMVH5enSL9oTFUpfTiJoyep2Yap23+CH9aQv9k+gIXqLovJ8GSvHQwA7U7+EU5KVvdx+BxkaJVYMxiyvIpXBhaCC19WRnRN3C7Ru0dzy/sN/ajXEXgcTf3XkNJMBfPNy/cOapcnbSJr0eDbyOdSg9iINChGCf/qjij99bLBeWcxFwtkL9d0A2VbzOsHxwWPvRtJ3QqatNBNi1OYLMRFpaggLSepjDcP+6WLVt6gNP9Ln55dMOgvKS3X2oNDSRy7kHGQMkHncZREiC3AD2noqzIF8tKua61dJAgbyTi/gb9zFOcClTPDK3NFQ77gTR6PpxFp1F9QlSMWi3mmWh5/igDS6z1R7cQOjMs07W9QYeOzr1MuAjAOS7ydv7z9alImFRAmKrYoxsvdlzNjbrJr2VVJIxv+GcELZos4WY8RtyiHX/TTR428nwOA2dcHP/2T3RK1ds=
  - secure: r7oFtQ6w24md3WcPzWl5tCX+CZbufdTKaSKY6yASdlKgRuTIzcgAkZQzK02N7wZl5vutOpNXfFMAyZrkNNjy0QbtqM+xzehuOd+3QOfZpKoLliA7Lge8HifisQ87KMyIP3hMubOGDHyI3bKg8N88+euSx2jXEqpZ9YlFegt2toqL1xLRyFi2OOR4Kv65CpI0ggya6hcEMYYSQdYgkfvBpVJ0MDsjs5CHy3kO1TpAIRpfN0vI32bm+3R/F9e3ntuEwZxkehhrPV/SC7MJW+8kySf1E6d5YN7P8fVWpXO0Pa4lv2FZyj1WB87xPfwC31N2ACDQLbt9rX5PO641qjs0bjS+1nFssg2ACengpO5Q8BMhAdJLN9HMHbEBDakeR7b1jCgi6+/T0iM+TSnZfftpW/vczSjL+TurIUy4c5urFSRhYSJEGhDz+IvrBV5yZe9ej/0VW/L5Nr1rIp9rS9oHE12sj6F7v0cXQzadHIjcTmvd1D6RsX/hmvuL5xBylux13r5SiV+CZl+PUiHFHlYfpErwB+Oruf7J6LNz2M+QVYn3lwP8zQm0fUNNwAeKuWs/mO92o3yx0lBLySqc9GtGJb85Gr5WTnnzF51i/yqIngNe47zDqnRQBkTAPwTgAn2V5QpAizlrB0odVJDpKkeN63Wtsq8HYs/TNTUrRDvvCKI=
