language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: U+L2rPwzaMF1kZpOy6dtxK4oFiVAO0Xg+f1fxaFIivcMndW9AanpFKIqkNyLqjY+IKPckw72jbYNCPApogdj5wNFHqfOsmxwm9E6+CeyhlhCWjtOkAXdMNQrdlFs5DAQ9hWdHkDo4hUR5GYVqu+xor/9X6J3V672O1syoj3d/int2EQGIL72fndboK7yGNsbK833WvmQ4dHr6X1mZQ7wM+GSN7D0iIeTL6FFF2isfbuXWQ93+W0wVwrYcnvsdYW/DmvkE0lCElqywjKBHf/qGrRzo4kBKN7JVQ9alqciAKwphnE1QRQzqkvhx4zp/5V7LQ/C7V+NHzfgUHJUdqBB2Dct5S3U33YaJT3b9uU+nBBj0iFfbtVtyb0qgATPBQKjmBfSHVQAdyhRhYePEXCSP6eMDyKua2uxBIpqNS0hP06uhKv+G+V4xq77cBFETe0smXvdR5Hn75eVuUr0KzN5fvIqXGps5hp7AjVeHoxGOUq3d4kpW5fU+7ZjEQWGki/B/HqNE5K22tCl1jSmUdXotEIU5Bw75+XVPgXFNYZKHIqYWHJl0eC6xln+eGUwFDXsjJQlAGtvxi3Gssu6z5nLHh+y038JlPEVXHhjUXy1c7dVUzGv3EMhABu4AbRTY4mcfrVKvrWTw3TuIDpn58vqy54ab2q0I70Rm56caElFdTo=
