language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: Ou6h3SEvxwRBF1h2iDD8wZfHMtW4Orq67EmxOGPXYcNmWBe247dYKPaJ0C40FgT7BurraBC/2R+6hRHeillWqJzmDoAOdETyjxC4h5XpQSXVSri0kbb9fsM8iwwv2vsAHWbYtym9mpaqWD4DQixVUH1MSvqxu42whIIrALFVDMWiTXRue97SylaxsgbLZSPgm9L6uDpKrtOM2pauKYcRYBIcLxqMmmCsI3IE7jc9uWLflBlsIjuq3DqiOFp/JlPwaqi7GFRtRusFooGU2E+dfnmAZJ51Wy1LKm7nwmAYqGn1avmxlS2W/vfejlUCSuV2Ndn+ROxUn2qXCnowSsspoowvK8erHlgJQ8V4P8xjnkHhpsob1JEn+I7SwhY2k2L7xZbHNezGb7TKemOESCJTXOoHSH1hGI6ie0r/Tld8Getgd3JHLC8oHt2X1I3MmUDo6Wsp5Q3Ax0MT0C3i4OMarhk6DSv6Jl3GkFr6JA3AQbnF124tC7KIcRurTQVCsNMdkCzZvdrHD6GY5zcBX8eXBhf8v69r7KUOwHp13PN0RxgL+gBkS5b08DMNSw7whWlsm48dW3/BLoI/hZB8cgfxJrgQZZBsZpkuwFRRw5a60F7p9vfItrv7t88cVMVPAGzMwshX71yHxqKVdYXs4A7ivw4IolyKq5M8IDj5EXdD+kA=
  - secure: DlyptjcAofT3T7nwWUqXXoK55PO4IWehm7I6S+2unG313ePB8JOjuvFBusEwo+WNpAH4OhF1b2FP7FPYv776VQCIOgULJuyq33RKsQ+/7eGmsTPeat+hW79Fi1AgMIpPfzhiK+QLOmCLGAsts6uDIyWj8IGHLrtYmszrG1BuGGDDU324DWxhNnJC4lroV8BazmXAG8USf3ivPDJ4yFu1ehE+w+mlQUB9HGK7zTJGN6JzcohRovusWHfKSSxiOEhURmEeXdD9i5PBrP+wQUJCiWLhMrLEKaV5xMVxrzPOMCUFN+fNBq324/Rzc1XvxjwseeYdc24LBQ+RRwG341/HNu6m9f8Lpvw92a0av/gbN4+6kZero3i9xb7i2/koNyA+KaT3jBFpgl8ZOfrDBAEt3AOQ1e35TzHR1YK7zdsk7Mhrggn5TP+prVD9lNc+kg16uYUiW9vZxXfv84Zt1+4ySj4cfqoqx7syR+ghAn+sVb3dIQICWp2PtW8tqt4ydehnj2fY+V8WsUGZ73nQzMnz9Mg8XcJ2jaTacr43cz52xGIUNE3B/3iJcnVNFiQmZPA21yqzW2qWsqcLK8OHBGw+t41Fcn2xVmF27qTa0zeZfqBCrcc0fDajCZCpcabfp3G5WTYenGEUVS3Ccp89GGuiU0jQy6ULqZ7Pg7HOXuDZ5Zc=
