language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: KwjCFSyzxdLDjcOt2O+BALc2KR+ooZUUO9k6CmLL3fjFkwP3CSyAOFevgvd2hQ9QA6lTmJswsENPJ9J4jrp/c/3HPXwDMOsnZOORSIkVv8a3tdw0h1rCeP94FWmfRXpaWBQwFes0FPBhKiHHchShF7RB1f9v/7VlyTQ7N4e/cHTUm5OQL15NgKgOyjFzKBSfmSjwUls3ZJinjPQhIibLA2rpXbIxRendQLMFFXSo9PrsdBvdoVP9hf9g/PsMtBoBtXl/8JfDIoS5azrF0IHbinMsfS9vi2+b8xuZpUAZtAqUAEvQ/zvwIUzCFbQ12eur7jtL7qpuYNEtCz+qIxQNE0euJbFu5zSZB/NodhbhPk6+KP/Vspz1Ji59kKznl9m51jxnzJeknKgBVwyiCBDSLp0wu0GNCx+lgiNs2N7NqVOxPvk1Wyv8HeDTIxTrgnYgbw7zJuWlGAKCIrGSlhZ61uu3NROkpG9FNbj7VZ7/C5SnV0KflxE1rPWofExJ2Ljh09PbBpCycHY2YHF4My/3tlxF0ftUhfCTYmvQ7LVVgNiNOVY0FpoZZ8P4W8DHDuomu5Iu1VDALK/W5wxagA99rWEGLuj5FvBrqgoxNDbmmuuVlFZ5hIAX7sZQAmyFxnv90qe4iy9lqKzD4U0GbnFM+OgvXQIU+s8AT9amH/ap4i0=
  - secure: KxUqebG0TfpR4LOLK5+lood2xF0YBfXOdi+eUL7z144Pggxc97JwU5chlqU4UvNDvzwaU9zDDOXDb8pkVC6H1a3VlavCey/kuljMf66HaIWDDmGLw9XrDsdP1GHm4X0EKUvatM9gUCkizS0t7nCgieBjz0u3Pti83/HIK6isgJwgfNTGhKCi3HpHRf8uUM7JIovOZKlEsTbXs++639xJ2IokbptJfF1alGrmvOUD0BWc7lEjlxACjJlYXVIOYF2xrTLYwdKRP80oj3isrVTZWHRIvojLB+uWU2C6rX+4YhYchkboFOAQicXoJWrPdcjSYQLmptDLGbCmYQaiTqlFLhi9NYMI6K5rqhAUeDJyCeK5Z6wDwXf04Jem0tmC+dFgK9xMcdS2a8uSipsLdS3r5WxjBNZRU1NdtvNNm+gWOBjeAFPUvvPcTyHYweKSfsjo3uQY8bbnyECOcgB33iRUCP3RlUgSRV+hce6ytdU9pMPA/gwavNBOj+VuStpV13B+V5CeeO6YotA4y1Z0G1YrxY94LJ0Bw5wYrxT4RbtsQgjGXp9Xp9y9Lf3uxIwkOiUUrGH+EK4swyMcSWK6slM1EhoQrPHLd8SUCjQoIvvlgyOFaOQmNxUCVo5VESCGJwi7v0gZtNDKGeNMMBgcO+x7UgnC0kqIgnZ71ZnedluzVRY=
