language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: "eI3cBXcXCKh6MCMZvE/e9t2JoVYn0KwHgCIYwMg822t7snLg2dVIfV50AiuJD8zrYuI29YJc/pH2s9kDgDXWH3g+j0+fmn7RKiRk9ScI9N0EewFSHOD2txmweYiGvRIt8aW6Z9+9RH43dZ+iEmZ2cCtG1PratACpnc+rvv0lDypb8CfhWGIkshcQ9GMkG77ytb8ccJGzbuN3KxVUqpoW5JNseV9PVQeJTytvplBsl4wSsY693QlfoP2AWH3MWoJIadlXOUQSIK2Y39aAVse2Wdn14tV8NNZzWuAJGiXithd+6LUs5WVuRtn0NM+Dshpjajt6y40X+TTbZe7Y2siHdwxYmpyyBE7QVYJA/bOxQRC9wnQedS3rlgnXVh2qD68q+CynbrLM6IhBgJNNvq5KmdSJQktyQnkDyQN6+wp8y20eqZ2wemjqRY7x2elP4EI3Nn8bBjL1F9TcG3sN7KHXI/YX7MDLEvCMioJhd9GVSCl1sW9U3kMO1aQS1i+1OOt6ngmNZHGIfNQOHeBeFp+J3Q3C/jDdCr1NWeEEKHpuY8zoDSFVHV0OcYu549FmYCO6cB5ff3ka4TsFFOlKiQVxCjA5tCEceKctuUjgzgbvwAaVx69TJTIQHhWDau/3TlXofJFQ3tu0o8M9bLFKP2dNvg+ZCK8WwxOgpip+4zfi+ZE="
  - secure: "mRqPpg5C0kPbkCQhotc0kB8GDMXHN3meejIzOKkyRbilx4GBKunK1V4LlyqpuXJVRGi5euphlaLmbjXJJfVn/TOzNftbwWuMeb4klqj+wfKrC8mxUnX+UMm+QLpcKmg3iNa48vbFc8sDvRHp8NjEkQh5ZKniQeZKF2FAYLOu9maezrOxj900MwOqL2EDfkr+Ny1huSSMm2QeiZmehHCvVIkMAjTVWNv8AoOBBzXRSsH/vMQtrYoFSFTuZkrderm1Pc/rnKhwZeeVfdXbtMwdADzY3X5Uy1OJovKuuvoNaEHevupaQE4WUWWmZXshoj4+4+QyFuqfxPfmvDBmltLWN57+Q2/NUAUw2ps/hPRQERir3elwwOkv0pAcLFVIMPpoFiA3T5xpa5D6v/l9gXZ7NBM+HQysxU+a3AJUlnNFL33bjoEAw1rT1Mr0vs0wK20gvD3dd55mxow1BZf9RbNuk5G26UbN+rExjOcMZ0emwb4RqKZYUG5hsIytdcg37rQj9iNNBLgwoujrgXIeGlAFMqLNXjv0ZHUwhMxceiqwSoJR/ayLjtfO+DG0eQR2VDal6IZYvCaYMT7CDpm77lUjTbtScB+wylMrXeFQoh68eVAeFHIgbHwrBL6nLnn/jOG4QQGnKdQFY0eF/vR9VkhhPAdsdTdjNI0c8ImBFB4esiU="
  