language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: ukuWhBG9auAihU+4h+NNHFceoLhNfrkqtob/X28nS6TvB5BbHi/aZFAlX8o/CiS3cXkaTwtDppXeyLks1CaIr61gZwraDOcZZJ4tZBUeOEoIrzF7ZITD0plqNMOHKxhkOM+eFWyLAiIi0F/M0Z9Og2XGDM4daNRaii51Fmd85MA4kG5wrfL3MSyr3XxgdMMFNRpkSp8w9cpQhTjs6/E1KCzxX0jwkjPcf/NN+gZWE9nDTNJuQ5enn3vlu+sgDKgLEk6frqagFYTyCfhlcGaeEw4lpgip/aBrkmYqVp0dhuBh2mogLKxD0lSRyiNMKxIi4zsfknbFRR3mE6isiIQx5A9hrCEXxRAGXZMXEGHNXP8LV4JDqWUDbuY7079VsuogRfZfXFh4Jv+1FU+nXoGNXUl8zIrpekI87EjAayMQB2MhwDvFRkNv1muRkFLojnSjqaZA4I2AtS2uVjlLRAwMKh9fbYx4dzY3AeoqIa+EKFZjayo0KPoBpUeqFZZo8f3ylGtWXFuWywVWgl+UDSYSsZLofUbmhb1rwZ0K0dgD8kDxaIo4pNjpGobsx1t7BD6R7rCu8UgI58XXvhWWKnKS/IQJjzSrs2Ghx2/4On9rYK7S8RubMhzxkLdpQ4Zda9TJf5CWhXCR4LEzMYGZgkLv7czFEzyYzVQujVJ9EyQ66PQ=
  - secure: Bb6MXmWh1+yk+1cvUci3Jilib93crDyFqrwo+855JptrxxydFhjA0TZtDd9+aZkNnR28E8CDr3dFF8Mva/KPLtCHsltulusptJCHZB7ve6DEQC6+M13LOZsYMpRrZ0b01+0hooQfex2utsTmGVTSICsxA5td3GvAL2nfLVgh2oKj9G7CC3IIfiwBTEmnG0IdPhtnU33XjJBJP1S/v9QnTwaD6Yvz3FDVoF46BCwhnAXuXtAyNqRa7/eoGR5O7eVoIn6J4Ev+kfYVRly2pFNEeEHYRik4GtbMrum+VV7Auh5IbZEekhChdO9HiLGMerbQ3OpfHjviieLKdPGGMpp9VIbt8q8PZMrZ6CbOZycz7fWcyQnchGg7FmCY2vN/L8r4UozuRmlzmAO0N1j28MU++awvF2F6HHxQzrtyUTIX8ky8fFB6AgYOcWn+mS/3kVt2HHYuCOoYD9l/HHiM9svSqvWnGHJGdlQ5xTbwrljwIYzG6jlePtZ26059ClzhnFjUBkYl9VKvzaYpa+dqH/DQivRFdYFcpBLTCh147ob9cPh+CrGNGDpJ1Jzp2rkKmGUnko7RtUXvbiH724NFL2PmRUFPRYwypzfQLLePPFPE7IdX4A7HtHUGAEX3N9fyVFt4NvIrAQORi9qoKKpMrIMjPEa9lf6hlXTne3BwMHm+GJA=
