language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: JcIQLbyG0iJYA8ucWy3vnq94KyFNz5tNA3evx0GK4wWM9g8+ry/piQGo90drB5uHtVxX2xzg0ANdcLJ16UN0WBki6mEVKqn/A2cPchzKfEuwiIFHRC861TVddVXJpNsLQbWxYW7PrVHl+rAPqv7j7Ev5YLtnKoQJjgRZVd1+AJ3WbZ+fNJDcpw8T4eFFlGzgFskLVe3dPLLJ00MwbAr7o6l794DrBvd99fhq+xfz6XB/RJ99mpzu1vBv6lqKh/qsE+Jjuy7fukdlHRHUJD+gj8wb/voBrx+CwPofdFot94zdwylsZmMD2rNFCYONN7lfqNLXueBdGaDXGQVgwj14MbXxbgjJ6+YHsRl0mBBBWvXQPwMH0VekoGv7Q9KOyos3NAHltuf8wOYl+swH/yMWsVNTEPGpFObFt/Vb8dDeq2x3X7qGiFJIsu1/nGPockf5eJcpM5kvbOX8dhE+wLz5T7fFeV3n8ItDlyYYSSRQoW8vJ2FPhQG8OE3s6AiC2nCIxWniPiwSJI1SnE37Kp3ey0uCGjL+eyPscDRC634J8vCzZTrlZO06vNscoYT+ItOunj2P0F5m8S7MZhlYGYeOTwCqjr07B+TsFIbW6R2eR8VkDVTjEbJ1COhsb70joafgNxqaTJ7SA8749O8iFIz7TH1dFNsGZgLVL2TzTOBrIM8=
  - secure: Vmur7WM4PSciEaxW45RRy2yovKU1D/47gawyw1o9RBaChgAs/H4Fd+3ca5WxyfgTXUucghBqYGNROEvtXxq9/CiUjLKjbTG8rMji+598zeOIc7ZG6JzVj/q9F/my/F1ZXMUA2Nb1co8hyF4HSWR4Cj+fDIaSGg8LXPrZnfnK+J4jBl870+ekYQ6JC5BG6Sei4K1PfYFsxfFSd5Z4C21KEojcCkjMPZqxKxmXsgJ26Mn1C9sHdXTK25AHel41qjDedmcL+wrlIRzDKB271y3i+mU+TkP4BCN/J7Tll6+x5XvN5gQdL+uP5/fl43fMhKVPSA5V2c0DmIsWMYNyfJMfYjJQOWH1t3gQ8XpTfoUUQWHaSP8MSiMGAzZZLOMN6NB0AzUUiU+d9e1KLJM9XbSIY6Y2F/QbX28xvBt7mLoBJTAQNfePILreZeZsCHVp8QmR9QufRUwOUD2cwQbHyXRjued4GmNq168+4SSEh8AGy/I1iqcyQ1eMDvSpGEkEM6YLaSbZeaKkx47GfIOggjjRo6/VVEz5WCAhJkEyq9BeEq4hbEBa9c9HYb2f6gO1u3pkfKRAoE9ZT3XVvsmud6mWryU6sbT67yBfD+4SCUiPxZOI+NyPhHepRSTL2Ybjv4H0/SL8ftD7AQ6wlcb9BCq6U2X096cnNms8WYu60yP+/mE=
